### ISSUE TITLE
move over VAMP etc

### ISSUE THREAD

**Issue by brookehus** [scikit-time/scikit-time#12]
- [x] VAMP
- [x] Koopman reweighting

**Comment by marscher** [comment]
Koopman reweighted TICA is done by a two step estimation, first the equillibrium correction is computed from the data, then the data is reweighted using this correction during the estimation of the covariance matrices. In PyEMMA the user did not have to construct both estimators and pass the data twice due to the streaming approach.
I'm going to move over the functionality, but we need to think about how to make it easy to use.
