### ISSUE TITLE
pcca and reactive flux

### ISSUE THREAD

**Issue by clonker** [scikit-time/scikit-time#19]
is it desired to have these as sort of stand-alone models? should we provide thin estimators?

**Comment by marscher** [comment]
On 30.07.19 07:34, Moritz Hoffmann wrote:
> is it desired to have these as sort of stand-alone models? should we provide thin estimators?
> 

These estimators would take a model as input (MSM). At least for PCCA we 
could think of encapsulating it in the MSM, because I believe it has 
never been used as a sole instance, but always through the MSM interface.

The reactive flux thing is a different thing, so maybe we should provide 
an estimator for this.
